### PR TITLE
Ensure we attach a cover sheet for STIN documents upon e-Filing

### LINKED ISSUE #684: BUG: STIN document not included on e-filed petition; just the cover sheet
**Describe the Bug**

PDFs served to the IRS for STIN for e-Filed petitions are only the cover sheet. They are missing the actual STIN file. 

**Business Impact/Reason for Severity**

The IRS requires the STIN to process the case properly

**In which environment did you see this bug?**

USTC IRS env; able to recreate in USTC Staging

**Who were you logged in as?**

petitioner creating a petition, docket clerk serving the petition

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

petitioner creating a petition, docket clerk serving the petition

**To Reproduce**

1. Petitioner create a new petition/case, using a STIN
2. Docket processes the petition/case
3. Serves the STIN to the IRS 
4. Generated PDF only has the cover sheet

NOTE: Paper petition with upload works

**Expected Behavior**

The PDF should have the cover sheet and the STIN

**Actual Behavior**

The PDF only has the cover sheet

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

### PR DESCRIPTION
**Pull request by mmarcotte**
To help resolve #684 , attach a coversheet to the STIN file. We already knew its UUID, but it wasn't part of the response from the server after filing a petition. Write a couple of tests to make sure we perform the correct number of cover sheet attachments.

### CODE REVIEW

**Review by rachaelparris — APPROVED** [review]

File: shared/src/business/useCases/filePetitionInteractor.js [hunk 1]
```diff
@@ -78,11 +78,19 @@ exports.filePetitionInteractor = async ({
...
+      ownershipDisclosureFileId: await ownershipDisclosureFileUpload,
+      petitionFileId: await petitionFileUpload,
+      petitionMetadata,
+      stinFileId: await stinFileUpload,
+    });
+
+  return {
+    caseDetail,
+    stinFileId,
+  };
```
Comment (adunkman) [inline shared/src/business/useCases/filePetitionInteractor.js:98]: While this functions correctly, there’s some goofy syntax going on with `await`-ing on resolved promises — by the time we pass `await Promise.all(…)` on line 75, we have already resolved all the above promises. Instead, we can capture the values from line 75 and use it below: 

```javascript
const [ ownershipDisclosureFileId, petitionFileId, stinFileId ] = await Promise.all([
  ownershipDisclosureFileUpload,
  petitionFileUpload, 
  stinFileUpload,
]);
```

**Review by adunkman — APPROVED** [review]
Looks good! One comment on code style, take it or leave it!

File: shared/src/business/useCases/filePetitionInteractor.js (hunk 1 above)
Comment (mmarcotte) [reply shared/src/business/useCases/filePetitionInteractor.js:98]: Totally agree. I started to go down this path, but went too far. I've simplified based on your suggestion. Totally comfortable that await `<undefined>` still resolves to `<undefined>`. Much more readable head to toe. 🙏
